import type { Metadata } from "next";
import "./globals.css";
import "remixicon/fonts/remixicon.css";
import Footer from "./components/Footer";
import Header from "./components/Header";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={` antialiased mx-auto w-full md:bg-black max-w-[420px]`}
            >
                <div
                    className="flex flex-col relative h-screen rounded-3xl "
                    style={{
                        background: "linear-gradient(to bottom, #DEF4F7 0%, #FFFFFF 35%, #FFFFFF 75%, #DFFAFE 100%)"

                    }}
                >
                    <main className="flex-1 overflow-y-auto pb-16  scrollbar-hide ">
                    <Header />

                        {children}
                    </main>

                    <Footer />
                </div>
            </body>
        </html>
    );
}
