import type { Metadata } from "next";
import "./globals.css";
import "remixicon/fonts/remixicon.css";
import Footer from "./components/Footer";
import Header from "./components/Header";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={` antialiased mx-auto w-full md:bg-black md:max-w-[420px] font-noto-sans`}
            >
                <div
                    className="flex flex-col relative md:rounded-3xl pb-4"
                    style={{
                        background: "linear-gradient(to bottom, #D3EFF3 0%, #FFFFFF 45%, #FFFFFF 70%, #DFFAFE 100%)",
 height: "100vh",
                    }}
                >
                    <Header />
                    <main className=" pb-[50px]  overflow-y-auto scrollbar-hide ">

                        {children}
                    </main>

                    <Footer />
                </div>
            </body>
        </html>
    );
}
